import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GlobalSideBar from "@/components/GlobalSideBar";
import TopBar from "@/components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex">
      <GlobalSideBar />
      <div className="overflow-y-auto h-screen w-full">
        <TopBar />
      {children}
      </div>
    </div>
  )
}
